spring:
  application:
    name: docker-demo
  postgres:
    name: app
    username: user
    password: passsword
  datasource:
    url: jdbc:postgresql://postgres:5432/app
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true