spring:
  application:
    name: docker-demo
  datasource:
    url: jdbc:postgresql://postgres-service:5432/app
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    root: INFO
    com.tristan.docker_demo: DEBUG
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] [%thread] %logger{36} - %msg%n"