apiVersion: apps/v1
kind: Deployment

metadata:
  name: todo-api-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: todo-api

  template:
    metadata:
      labels:
        app: todo-api

    spec:
      containers:
        - name: todo-api
          image: todo-api:local
          # Use IfNotPresent to avoid pulling from registry during local testing
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080