name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: "temurin"

    - name: Make mvnw executable
      run: chmod +x ./mvnw

    - name: Build with Maven
      run: ./mvnw clean package -DskipTests

    - name: Build and run Docker Compose
      run: docker compose -f docker-compose.yml up --build -d

    - name: Push Docker to GitHub Container Registry
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
        