name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: "temurin"

    - name: Make mvnw executable
      run: chmod +x ./mvnw

    - name: Build with Maven
      run: ./mvnw clean package -DskipTests

    - name: Build and run Docker Compose
      run: docker compose -f docker-compose.yml up --build -d

    - name: Make scripts executable
      run: chmod +x ./scripts/*.sh

    - name: Wait for API to be ready
      run: ./scripts/wait-for-api.sh

    - name: Test API
      run: ./scripts/test-api.sh

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker to GitHub Container Registry
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
        
    - name: Stop Docker Compose
      if: always()
      run: docker compose -f docker-compose.yml down